FROM alpine:3.21

RUN apk add --no-cache python3 py3-pip
RUN pip install --break-system-packages requests pydantic

RUN addgroup -S stos
RUN adduser -S stos -G stos

ENV MASTER_URL=http://master:80
ENV GUI_URL=https://igrzyska.eti.pg.gda.pl
ENV QUEUE_NAMES="stos2025,stos2025-python"

WORKDIR /app
COPY adapter/adapter.py .
COPY common/ ./common/


USER stos:stos
ENTRYPOINT ["python3", "-u", "adapter.py"]

#docker build -t adapter ./src/adapter
