FROM alpine:3.14

RUN apk add --no-cache python3 py3-pip
RUN pip install flask flask-restx

WORKDIR /app
COPY stos.py .

EXPOSE 2137

ENTRYPOINT ["python3", "-u", "stos.py"]


#docker build -t mock ./src/mock
