FROM docker:dind

RUN apk add --no-cache python3 py3-pip
RUN pip install --break-system-packages fastapi uvicorn python-multipart

RUN addgroup -S workergroup
RUN adduser -S workeruser -G workergroup

WORKDIR /app
COPY worker.py .

ENV WORKER_ID=0
EXPOSE 80

# ENTRYPOINT ["python3", "-u", "worker.py"]
ENTRYPOINT ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "80"]


#docker build -t worker ./src/worker
