FROM alpine:3.21

# setting up working directory
WORKDIR /app


# metadata
LABEL org.opencontainers.image.title="stos_worker"
LABEL org.opencontainers.image.description="Worker service for STOS project, responsible for executing tasks and managing data."
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.authors="Damian Trowski <damiantrowski.c@gmail.com>"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/Stos-2025/Projekt_Inzynierski-2025"
LABEL org.opencontainers.image.documentation="https://github.com/Stos-2025/Projekt_Inzynierski-2025"


# coping files
COPY worker/src/* .
COPY common/*.py ./common/


# installing dependencies
RUN apk add --no-cache python3 py3-pip py3-requests py3-pydantic py3-docker-py py3-natsort
RUN pip install --break-system-packages ansi2html


# setting up user
RUN addgroup -S stos
RUN adduser -S stos -G stos
USER stos:stos


# setting up entrypoint
ENTRYPOINT ["python3", "-u" , "worker.py"]
