FROM alpine:3.20

WORKDIR /app

COPY requirements.txt .
RUN apk add --no-cache python3 py3-pip && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    rm -rf /var/cache/apk/*

