FROM alpine:3.20

RUN apk add --no-cache python3 py3-pip
RUN pip install --break-system-packages fastapi uvicorn python-multipart sqlalchemy

RUN addgroup -S taskgroup
RUN adduser -S taskuser -G taskgroup

WORKDIR /app
COPY task.py .


ENTRYPOINT ["uvicorn", "task:app", "--host", "0.0.0.0", "--port", "80"]

#docker build -t tasks ./src/tasks
