FROM alpine:3.21

# setting up working directory
WORKDIR /app


# metadata
LABEL org.opencontainers.image.title="stos_master"
LABEL org.opencontainers.image.description="Master service for STOS project, responsible for crud-ing submissions."
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.authors="Damian Trowski <damiantrowski.c@gmail.com>"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source="https://github.com/Stos-2025/Projekt_Inzynierski-2025"
LABEL org.opencontainers.image.documentation="https://github.com/Stos-2025/Projekt_Inzynierski-2025"


# coping files
COPY master/app/* .
COPY common/*.py ./common/


# installing dependencies
RUN apk add --no-cache python3 py3-requests py3-python-multipart py3-sqlalchemy py3-pip
RUN pip install --break-system-packages uvicorn fastapi 

# setting up user
RUN addgroup -S stos
RUN adduser -S stos -G stos
USER stos:stos


# setting up envs
ENV MASTER_API_KEY=MASTER_API_KEY


# setting up entrypoint
ENTRYPOINT ["uvicorn", "master:app", "--no-access-log", "--host", "0.0.0.0", "--port", "80"]










