FROM alpine:3.20

RUN apk add --no-cache python3 py3-pip
RUN pip install fastapi uvicorn python-multipart

RUN addgroup -S mastergroup
RUN adduser -S masteruser -G mastergroup

WORKDIR /app
COPY master.py .
COPY master-controller.py .
COPY submission.py .

ENV WORKER_URLS="http://worker:80"

ENTRYPOINT ["uvicorn", "master-controller:master_app", "--host", "0.0.0.0", "--port", "80"]

#docker build -t master ./src/master
