FROM node:23.2.0-alpine3.20 AS build

WORKDIR /app

COPY stos-frontend/package.json stos-frontend/package-lock.json ./
RUN npm install

COPY stos-frontend . 

RUN npm run build --prod

FROM nginx:alpine

COPY --from=build /app/dist/stos-frontend /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

#docker build -t stos-frontend src/frontend