services:
  worker:
    image: stos_worker
    restart: always
    build:
      dockerfile: worker/dockerfile
    volumes:
      - ${STOS_FILES}/shared:/shared:rw
      - ${STOS_FILES}/workers:/workers:rw
      - ${DOCKER_SOCK}:/var/run/docker.sock:rw
    environment:
      - WORKERS_DATA_LOCAL_PATH=/workers
      - WORKERS_DATA_HOST_PATH=${STOS_FILES}/workers
      - EXEC_IMAGE_NAME=${EXEC_IMAGE_NAME}
      - JUDGE_IMAGE_NAME=${JUDGE_IMAGE_NAME}
      
      - GUI_URL=${GUI_URL}
      - QUEUE_NAMES=${QUEUE_NAMES}
      - QUEUE_COMPILER_DICT=${QUEUE_COMPILER_DICT}
    group_add:  
      - ${DOCKER_GID}
      - ${STOS_GID}
    deploy:
      mode: replicated
      replicas: 4

  gui_mock:
    image: gui_mock
    build:
      dockerfile: gui_mock/dockerfile
    ports:
      - "8081:80"
