services:
  # --- worker ---
  worker:
    image: stos_worker
    restart: always
    build:
      dockerfile: worker/dockerfile
    volumes:
      - ${STOS_FILES}:/workers:rw
      - ${DOCKER_SOCK}:/var/run/docker.sock:rw
    environment:
      - WORKERS_DATA_LOCAL_PATH=/workers
      - WORKERS_DATA_HOST_PATH=${STOS_FILES}
      
      - GUI_URL=${GUI_URL}
      - LOKI_URL=${LOKI_URL}

      - USED_QUEUES=${USED_QUEUES}
      - DEFAULT_EXEC_IMAGE=${DEFAULT_EXEC_IMAGE}
      - DEFAULT_JUDGE_IMAGE=${DEFAULT_JUDGE_IMAGE}
      - DEFAULT_COMPILER_IMAGE=${DEFAULT_COMPILER_IMAGE}
      - QUEUE_EXEC_MAP=${QUEUE_EXEC_MAP}
      - QUEUE_JUDGE_MAP=${QUEUE_JUDGE_MAP}
      - QUEUE_COMPILER_MAP=${QUEUE_COMPILER_MAP}
      - LOGGER_NODE_NAME=${LOGGER_NODE_NAME}

      - STOS_GID=${STOS_GID}
      - IS_DEBUG_MODE_ENABLED=${IS_DEBUG_MODE_ENABLED}
    group_add:  
      - ${DOCKER_GID}
      - ${STOS_GID}
    deploy:
      mode: replicated
      replicas: 4

  # gui_mock:
  #   image: gui_mock
  #   build:
  #     dockerfile: gui_mock/dockerfile
  #   ports:
  #     - "8080:80"






  # # --- NODE EXPORTER (monitoring hosta) ---
  # node_exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node_exporter
  #   ports:
  #     - "9100:9100"
  #   pid: host
  #   restart: unless-stopped


  # # --- cADVISOR (monitoring kontenerów) ---
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
      
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped

