services:
  worker:
    image: stos_worker
    restart: always
    depends_on:
      - master
    build:
      context: ..
      dockerfile: worker/dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${STOS_FILES}/shared:/shared:ro
      - ${STOS_FILES}/shared/workers:/workers:rw
      - ${DOCKER_SOCK}:/var/run/docker.sock:rw
    environment:
      - MASTER_URL=http://master:80
      - WORKERS_DATA_LOCAL_PATH=/workers
      - WORKERS_DATA_HOST_PATH=${STOS_FILES}/shared/workers
      - EXEC_IMAGE_NAME=${EXEC_IMAGE_NAME}
      - JUDGE_IMAGE_NAME=${JUDGE_IMAGE_NAME}
      - QUEUE_LANG_DICT=${QUEUE_LANG_DICT}
    group_add:  
      - ${DOCKER_GID}
    deploy:
      mode: replicated
      replicas: 3
     
  adapter:
    image: stos_adapter
    restart: always
    depends_on:
      - master
    build:
      context: ..
      dockerfile: adapter/dockerfile
    volumes:
      - ${STOS_FILES}/shared:/shared:rw
    environment:
      - MASTER_URL=http://master:80
      - GUI_URL=${GUI_URL}
      - QUEUE_NAMES=${QUEUE_NAMES}
      - LANG_COMPILER_DICT=${LANG_COMPILER_DICT}

  master:
    image: stos_master
    restart: always
    tty: true
    build:
      context: ..
      dockerfile: master/dockerfile
    environment:
      - WORKER_URLS=http://worker:80
    ports:
      - 8080:80

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"


#docker compose -f src/conf/compose.yml up