services:
  worker:
    image: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/workers/0:/data:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/shared:/shared:ro
    environment:
      - MASTER_URL=http://master:80     

  worker2:
    image: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/workers/2:/data:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/shared:/shared:ro
    environment:
      - WORKER_DATA_HOST_PATH=/home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/workers/2
      - MASTER_URL=http://master:80     
     
  
  tasks:
    image: tasks
    ports:
      - "8082:80"
    volumes:
      - /home/damian/Projekty/Projekt_Inzynierski-2025/src/conf/dbs:/data/db:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/tasks:/data/tasks:rw
  
  submissions:
    image: submissions
    ports:
      - "8083:80"
    volumes:
      - /home/damian/Projekty/Projekt_Inzynierski-2025/src/conf/dbs:/data/db:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/submissions:/data/submissions:rw

  master:
    image: master
    tty: true
    environment:
      - WORKER_URLS=http://worker:80
    ports:
      - 8080:80


#docker compose -f src/conf/compose.yml up