services:
  worker:
    image: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/workers/0:/data:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/shared:/shared:ro
    environment:
      - MASTER_URL=http://master:80     

  worker2:
    image: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/workers/2:/data:rw
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/shared:/shared:ro
    environment:
      - WORKER_DATA_HOST_PATH=/home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/workers/2
      - MASTER_URL=http://master:80     
     
  results:
    image: results
    volumes:
      - /home/damian/Projekty/Projekt_Inzynierski-2025/stos-files/shared:/data:rw
    ports:
      - 8081:80
  master:
    image: master
    tty: true
    environment:
      - WORKER_URLS=http://worker:80
    ports:
      - 8080:80


#docker compose -f src/conf/compose.yml up