services:
  worker:
    image: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${STOS_FILES}/workers/1:/data:rw
      - ${STOS_FILES}/shared:/shared:ro
    environment:
      - WORKER_DATA_HOST_PATH=${STOS_FILES}/workers/1
      - MASTER_URL=http://master:80     

  worker2:
    image: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${STOS_FILES}/workers/2:/data:rw
      - ${STOS_FILES}/shared:/shared:ro
    environment:
      - WORKER_DATA_HOST_PATH=${STOS_FILES}/workers/2
      - MASTER_URL=http://master:80     
     
  adapter:
    image: adapter
    volumes:
      - ${STOS_FILES}/shared:/shared:rw
    environment:
      - MASTER_URL=http://master:80
      - GUI_URL=${GUI_URL}

  master:
    image: master
    tty: true
    environment:
      - WORKER_URLS=http://worker:80
    ports:
      - 8080:80


#docker compose -f src/conf/compose.yml up