services:
  worker:
    image: stos_worker
    restart: always
    depends_on:
      - master
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${STOS_FILES}/shared:/shared:ro
      - ${STOS_FILES}/shared/workers:/workers:rw
      - ${DOCKER_SOCK}:/var/run/docker.sock:rw
    environment:
      - WORKERS_DATA_LOCAL_PATH=/workers
      - WORKERS_DATA_HOST_PATH=${STOS_FILES}/shared/workers
      - COMP_IMAGE_NAME=${COMP_IMAGE_NAME}
      - EXEC_IMAGE_NAME=${EXEC_IMAGE_NAME}
      - JUDGE_IMAGE_NAME=${JUDGE_IMAGE_NAME}
      - MASTER_URL=http://master:80
    group_add:  
      - ${DOCKER_GID}
    deploy:
      mode: replicated
      replicas: 3
     
  adapter:
    image: stos_adapter
    restart: always
    volumes:
      - ${STOS_FILES}/shared:/shared:rw
    environment:
      - MASTER_URL=http://master:80
      - QUEUE_NAMES=stos2025,stos2025-python
      - GUI_URL=${GUI_URL}

  master:
    image: stos_master
    restart: always
    tty: true
    environment:
      - WORKER_URLS=http://worker:80
    ports:
      - 8080:80


#docker compose -f src/conf/compose.yml up